name: 'pr-comment-sonarqube'
description: 'Pull Request Comment With Sonarqube Analysis'
inputs: 
  sonar.projectKey: 
    required: true
  sonar.host.url:
    required: true
  sonar.login:
    required: true
  sonar.metric:
    required: false
    default: bugs,security_hotspots
  github.token:
    required: true
  errorOnFail:
    required: false
    default: true
outputs:
  comment: 
    description: 'comment contents'
runs: 
  using: 'node16'
  main: 'dist/index.js'